using System;
using System.IO;
using System.Text;
using UndertaleModLib.Models;

EnsureDataLoaded();

// Runtime room order comes from GeneralInfo.RoomOrder (GMS2.3).
var order = Data.GeneralInfo.RoomOrder;
string txtPath = @"C:\Users\romeu\Documents\longo-doggo\recovered\analysis\room-instances.txt";
string cPath = @"C:\Users\romeu\Documents\longo-doggo\src\level_data.h";

var txt = new StringBuilder();
var c = new StringBuilder();

txt.AppendLine("Longo Doggo runtime room data (GeneralInfo.RoomOrder order; instances in stored creation order)");
txt.AppendLine("===================================================================");
txt.AppendLine($"Rooms in runtime order: {order.Count}");

c.AppendLine("/*");
c.AppendLine(" * Generated by recovered/analysis/DumpRoomData.csx from the recovered data.win.");
c.AppendLine(" * Rooms are listed in the original runtime order (GeneralInfo.RoomOrder),");
c.AppendLine(" * so room 0 is the GameMaker start room and room_goto_next() follows the array.");
c.AppendLine(" * Instances are in stored creation order with their instance-layer depth.");
c.AppendLine(" */");
c.AppendLine("#ifndef LONGO_DOGGO_LEVEL_DATA_H");
c.AppendLine("#define LONGO_DOGGO_LEVEL_DATA_H");
c.AppendLine();
c.AppendLine("/* GameMaker object_index values recovered from data.win.  The numeric order");
c.AppendLine(" * matches the original asset table (oMouse's editor palette depends on it). */");
c.AppendLine("typedef enum LongoObj {");
string[] objNames = new string[Data.GameObjects.Count];
for (int i = 0; i < Data.GameObjects.Count; i++)
{
    objNames[i] = Data.GameObjects[i].Name.Content;
    string id = ObjIdent(objNames[i]);
    c.AppendLine($"    LONGO_{id} = {i}{(i < Data.GameObjects.Count - 1 ? "," : "")}");
}
c.AppendLine("};");
c.AppendLine();
c.AppendLine("typedef struct LongoRoomInstance {");
c.AppendLine("    unsigned char object;");
c.AppendLine("    float x;");
c.AppendLine("    float y;");
c.AppendLine("    float xscale;");
c.AppendLine("    float yscale;");
c.AppendLine("    int depth; /* depth of the instance layer it was placed on */");
c.AppendLine("} LongoRoomInstance;");
c.AppendLine();
c.AppendLine("typedef struct LongoRoom {");
c.AppendLine("    const char *name;");
c.AppendLine("    int width;");
c.AppendLine("    int height;");
c.AppendLine("    const LongoRoomInstance *instances;");
c.AppendLine("    int instance_count;");
c.AppendLine("} LongoRoom;");
c.AppendLine();
c.AppendLine("#define LONGO_ROOM_COUNT " + order.Count);
c.AppendLine();

for (int ri = 0; ri < order.Count; ri++)
{
    UndertaleRoom room = order[ri].Resource;
    string name = room.Name.Content;
    string ident = name.Replace("rm_", "");
    txt.AppendLine();
    txt.AppendLine($"RUNTIME ROOM {ri}: {name}  size={room.Width}x{room.Height}");

    c.AppendLine($"static const LongoRoomInstance longo_room_{ident}_instances[] = {{");

    // instances in stored order, resolved to their layer depth
    var layerById = new System.Collections.Generic.Dictionary<uint, UndertaleRoom.Layer>();
    foreach (var layer in room.Layers)
        layerById[layer.LayerId] = layer;

    foreach (var inst in room.GameObjects)
    {
        int depth = FindLayerDepth(room, layerById, inst);
        string objId = ObjIdent(objNames[Data.GameObjects.IndexOf(inst.ObjectDefinition)]);
        c.AppendLine($"    {{ LONGO_{objId}, {Fmt(inst.X)}, {Fmt(inst.Y)}, {Fmt(inst.ScaleX)}, {Fmt(inst.ScaleY)}, {depth} }},");
        txt.AppendLine($"  id={inst.InstanceID} {objNames[Data.GameObjects.IndexOf(inst.ObjectDefinition)]} at ({inst.X},{inst.Y}) scale=({inst.ScaleX},{inst.ScaleY}) layerDepth={depth}");
    }

    c.AppendLine("};");
    c.AppendLine();
    c.AppendLine($"static const LongoRoom longo_room_{ident} = {{");
    c.AppendLine($"    \"{name}\", {room.Width}, {room.Height},");
    c.AppendLine($"    longo_room_{ident}_instances,");
    c.AppendLine($"    (int)(sizeof(longo_room_{ident}_instances) / sizeof(longo_room_{ident}_instances[0]))");
    c.AppendLine("};");
    c.AppendLine();
}

c.AppendLine("/* Runtime room table: index 0 is the GameMaker start room; room_goto_next()");
c.AppendLine(" * walks this array.  oTransition.object_num starts at 1 on the title room. */");
c.AppendLine("static const LongoRoom *const longo_rooms[LONGO_ROOM_COUNT] = {");
for (int ri = 0; ri < order.Count; ri++)
{
    UndertaleRoom room0 = order[ri].Resource;
    string ident = room0.Name.Content.Replace("rm_", "");
    c.AppendLine($"    &longo_room_{ident}{(ri < order.Count - 1 ? "," : "")}");
}
c.AppendLine("};");
c.AppendLine();
c.AppendLine("#endif /* LONGO_DOGGO_LEVEL_DATA_H */");

File.WriteAllText(txtPath, txt.ToString(), Encoding.UTF8);
File.WriteAllText(cPath, c.ToString(), Encoding.UTF8);
ScriptMessage($"Wrote {txtPath} and {cPath}");

// helpers defined after usage in csx are fine
string ObjIdent(string n)
{
    if (n == "obj_bloom_appsrf") return "BLOOM";
    if (n == "par_module") return "PAR_MODULE";
    string stem = n.StartsWith("o") ? n.Substring(1) : n;
    return "OBJ_" + stem.ToUpperInvariant();
}
string Fmt(float f) => f.ToString(System.Globalization.CultureInfo.InvariantCulture);

int FindLayerDepth(UndertaleRoom room, System.Collections.Generic.Dictionary<uint, UndertaleRoom.Layer> byId, UndertaleRoom.GameObject inst)
{
    foreach (var layer in room.Layers)
    {
        if (layer.LayerType == UndertaleRoom.LayerType.Instances && layer.InstancesData != null)
        {
            foreach (var li in layer.InstancesData.Instances)
            {
                if (li == inst) return (int)layer.LayerDepth;
            }
        }
    }
    return 0;
}
